# .github/workflows/deploy-backend.yml
name: Deploy Backend

on:
  push:
    branches: [main]
    paths: ["backEnd/**", ".github/workflows/deploy-backend.yml"]

jobs:
  # Wait for tests to pass first
  wait-for-tests:
    name: Wait for Tests
    runs-on: ubuntu-latest
    steps:
      - name: Wait for test workflow
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: "test-backEnd-index" # One of your test jobs
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  deploy-backend:
    name: 🚀 Deploy Backend
    runs-on: ubuntu-latest
    needs: [wait-for-tests]
    steps:
      - name: Deploy to Render
        run: |
          echo "🚀 Deploying backend..."
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}"

      - name: Wait and health check
        run: |
          echo "⏳ Waiting for deployment..."
          sleep 60

          for i in {1..10}; do
            if curl -f "${{ secrets.BACKEND_URL }}/health"; then
              echo "✅ Backend deployed successfully!"
              exit 0
            fi
            echo "⏳ Health check $i/10..."
            sleep 15
          done
          echo "❌ Deployment failed!"
          exit 1
