# .github/workflows/test.yml
name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup Dependencies
    runs-on: ubuntu-latest
    outputs:
      backend-cache-hit: ${{ steps.cache-backend.outputs.cache-hit }}
      frontend-cache-hit: ${{ steps.cache-frontend.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Cache Backend Dependencies
        id: cache-backend
        uses: actions/cache@v4
        with:
          path: backEnd/node_modules
          key: ${{ runner.os }}-pnpm-backend-${{ hashFiles('backEnd/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-backend-

      - name: Cache Frontend Dependencies
        id: cache-frontend
        uses: actions/cache@v4
        with:
          path: frontEnd/node_modules
          key: ${{ runner.os }}-pnpm-frontend-${{ hashFiles('frontEnd/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-frontend-

      - name: Install Backend Dependencies
        if: steps.cache-backend.outputs.cache-hit != 'true'
        working-directory: ./backEnd
        run: pnpm install --frozen-lockfile

      - name: Install Frontend Dependencies
        if: steps.cache-frontend.outputs.cache-hit != 'true'
        working-directory: ./frontEnd
        run: pnpm install --frozen-lockfile

  # Detect changes to optimize which jobs run
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            backend:
              - 'backEnd/**'
              - '.github/workflows/test.yml'
            frontend:
              - 'frontEnd/**'
              - '.github/workflows/test.yml'

  # Backend tests - run in parallel
  test-backend:
    runs-on: ubuntu-latest
    needs: [setup, changes]
    if: needs.changes.outputs.backend == 'true'
    strategy:
      fail-fast: false
      matrix:
        test-suite:
          [
            index,
            dataRoute,
            planillaRoute,
            oficialRoute,
            personalEmpresaRoute,
            personalSeguridadRoute,
          ]
    defaults:
      run:
        working-directory: ./backEnd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: backEnd/node_modules
          key: ${{ runner.os }}-pnpm-backend-${{ hashFiles('backEnd/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-backend-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test:${{ matrix.test-suite }} --exit

  # Frontend linting and testing
  test-frontend:
    runs-on: ubuntu-latest
    needs: [setup, changes]
    if: needs.changes.outputs.frontend == 'true'
    defaults:
      run:
        working-directory: ./frontEnd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: frontEnd/node_modules
          key: ${{ runner.os }}-pnpm-frontend-${{ hashFiles('frontEnd/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-frontend-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: pnpm lint

      - name: Run type checking
        run: pnpm type-check

      - name: Run tests (if available)
        run: pnpm test --run
        continue-on-error: true
