name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  avoid_redundancy:
    name: Cancel Workflow
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  dependenciesBack:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backEnd
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

  dependenciesFront:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontEnd
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

  test-backEnd-index:
    runs-on: ubuntu-latest
    needs: [avoid_redundancy, dependenciesBack]
    defaults:
      run:
        working-directory: ./backEnd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Run index tests
        run: npm run test:index

  test-backEnd-dataRoute:
    runs-on: ubuntu-latest
    needs: [avoid_redundancy, dependenciesBack]
    defaults:
      run:
        working-directory: ./backEnd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Run dataRoute tests
        run: npm run test:dataRoute

  test-backEnd-planillaRoute:
    runs-on: ubuntu-latest
    needs: [avoid_redundancy, dependenciesBack]
    defaults:
      run:
        working-directory: ./backEnd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Run planillaRoute tests
        run: npm run test:planillaRoute

  lint-frontend:
    runs-on: ubuntu-latest
    needs:
      [
        avoid_redundancy,
        test-backEnd-index,
        test-backEnd-planillaRoute,
        test-backEnd-dataRoute,
        dependenciesFront,
      ]
    defaults:
      run:
        working-directory: ./frontEnd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run frontend tests
        run: npm run lint
