name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Install Dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.3

      - name: Configure pnpm
        run: echo "node-linker=hoisted" >> .npmrc

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            backEnd/node_modules
            frontEnd/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('backEnd/pnpm-lock.yaml', 'frontEnd/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd backEnd && pnpm install
          cd ../frontEnd && pnpm install

  test-backEnd-index:
    runs-on: ubuntu-latest
    needs: [setup]
    defaults:
      run:
        working-directory: ./backEnd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.3
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: backEnd/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('backEnd/pnpm-lock.yaml') }}
      - name: Run index tests
        run: pnpm test:index

  test-backEnd-dataRoute:
    runs-on: ubuntu-latest
    needs: [setup]
    defaults:
      run:
        working-directory: ./backEnd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.3
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: backEnd/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('backEnd/pnpm-lock.yaml') }}
      - name: Run dataRoute tests
        run: pnpm test:dataRoute

  test-backEnd-planillaRoute:
    runs-on: ubuntu-latest
    needs: [setup]
    defaults:
      run:
        working-directory: ./backEnd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.3
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: backEnd/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('backEnd/pnpm-lock.yaml') }}
      - name: Run planillaRoute tests
        run: pnpm test:planillaRoute

  test-backEnd-oficialRoute:
    runs-on: ubuntu-latest
    needs: [setup]
    defaults:
      run:
        working-directory: ./backEnd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.3
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: backEnd/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('backEnd/pnpm-lock.yaml') }}
      - name: Run oficialRoute tests
        run: pnpm test:oficialRoute

  test-backEnd-personalEmpresaRoute:
    runs-on: ubuntu-latest
    needs: [setup]
    defaults:
      run:
        working-directory: ./backEnd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.3
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: backEnd/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('backEnd/pnpm-lock.yaml') }}
      - name: Run personalEmpresaRoute tests
        run: pnpm test:personalEmpresaRoute

  test-backEnd-personalSeguridadRoute:
    runs-on: ubuntu-latest
    needs: [setup]
    defaults:
      run:
        working-directory: ./backEnd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.3
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: backEnd/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('backEnd/pnpm-lock.yaml') }}
      - name: Run personalSeguridadRoute tests
        run: pnpm test:personalSeguridadRoute

  lint-frontend:
    runs-on: ubuntu-latest
    needs: [setup]
    defaults:
      run:
        working-directory: ./frontEnd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.3
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: frontEnd/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('frontEnd/pnpm-lock.yaml') }}
      - name: Run frontend lint
        run: pnpm lint
